
import java.awt.Component;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.ProgressMonitor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nandu6177
 */
public class HomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindow
     */
    public HomeWindow() {
        initComponents();
        AUsernameField.setText("Admin");
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SUsernameField = new javax.swing.JTextField();
        SPasswordField = new javax.swing.JPasswordField();
        Slogin = new javax.swing.JButton();
        SClear = new javax.swing.JButton();
        P1 = new javax.swing.JProgressBar(0,100);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FUsernameField = new javax.swing.JTextField();
        FPasswordField = new javax.swing.JPasswordField();
        FLogin = new javax.swing.JButton();
        FClear = new javax.swing.JButton();
        P2 = new javax.swing.JProgressBar(0,100);
        jPanel3 = new javax.swing.JPanel();
        APasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        AUsernameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AClear = new javax.swing.JButton();
        Alogin = new javax.swing.JButton();
        P3 = new javax.swing.JProgressBar(0,100);

        jScrollPane1.setViewportView(jTextPane1);

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel3.setText("Password");

        Slogin.setText("Login");
        Slogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SloginActionPerformed(evt);
            }
        });

        SClear.setText("Clear");
        SClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(SClear)
                .addGap(129, 129, 129)
                .addComponent(Slogin)
                .addGap(253, 253, 253))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(SUsernameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Slogin)
                    .addComponent(SClear))
                .addGap(18, 18, 18)
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Student Login", jPanel1);

        jLabel2.setText("Username");

        jLabel4.setText("Password");

        FUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FUsernameFieldActionPerformed(evt);
            }
        });

        FLogin.setText("Login");
        FLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FLoginActionPerformed(evt);
            }
        });

        FClear.setText("Clear");
        FClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FUsernameField)
                                    .addComponent(FPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(FClear)
                                .addGap(86, 86, 86)
                                .addComponent(FLogin)))
                        .addGap(0, 210, Short.MAX_VALUE))
                    .addComponent(P2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FLogin)
                    .addComponent(FClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Faculty Login", jPanel2);

        jLabel5.setText("Username");

        AUsernameField.setEditable(false);

        jLabel6.setText("Password");

        AClear.setText("Clear");
        AClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AClearActionPerformed(evt);
            }
        });

        Alogin.setText("Login");
        Alogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(AClear)
                .addGap(129, 129, 129)
                .addComponent(Alogin)
                .addGap(253, 253, 253))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(APasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(AUsernameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(APasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alogin)
                    .addComponent(AClear))
                .addGap(28, 28, 28)
                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin Login", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SloginActionPerformed
        // TODO add your handling code here:
        //ProgressMonitor P = new ProgressMonitor(this,"Authenticating","Connecting to Database...",0,100);
        String usr = SUsernameField.getText();
        String pwd = SPasswordField.getText();
        try {
            P1.setValue(10);
            //connect to database           
            Connection conn = null;
            ConnectDB DB=new ConnectDB();
            DB.connect();
            P1.setValue(50);
            //P.setNote("verifying");
            conn = DB.getconn();
            SearchModule s= new SearchModule();
            s.setconn(conn);
            int res = s.Login(usr,pwd,1);
            DB.disconnect();
            P1.setValue(100);
            System.out.println(res);
            if(res<1) {
                //P.close();
                IncorrectCredentialException cred= new IncorrectCredentialException("Incorrect Username/Password");
                throw cred;
            }
        } catch (IncorrectCredentialException er) {
            //P.close();
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Incorrect Username/Password");
            //Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        //P.close();
        //System.out.println("I am being executed idk why!");
        this.dispose();
        new ExamineeUI(usr).setVisible(true);
    }//GEN-LAST:event_SloginActionPerformed

    private void FLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLoginActionPerformed
        // TODO add your handling code here:
        P2.setValue(0);
        String usr = FUsernameField.getText();
        String pwd = FPasswordField.getText();
        try {
            //connect to database           
            Connection conn = null;
            P2.setValue(10);
            ConnectDB DB=new ConnectDB();
            DB.connect();
            conn = DB.getconn();
            P2.setValue(50);
            SearchModule s= new SearchModule();
            s.setconn(conn);
            int res = s.Login(usr,pwd,0);
            P2.setValue(100);
            DB.disconnect();
            System.out.println(res);
            
            if(res<1) {
                P2.setValue(0); 
                IncorrectCredentialException cred= new IncorrectCredentialException("Incorrect Username/Password");
                throw cred;
            }
        } catch (IncorrectCredentialException er) {
            Component frame = null;
            P2.setValue(0);
            JOptionPane.showMessageDialog(frame, "Incorrect Username/Password");
            //Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        //System.out.println("I am being executed idk why!");
        this.dispose();
        new ExaminerUI(usr).setVisible(true);
    }//GEN-LAST:event_FLoginActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
//        jPanel1.setVisible(true);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void FUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FUsernameFieldActionPerformed

    private void SClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SClearActionPerformed
        // TODO add your handling code here:
        SUsernameField.setText("");
        SPasswordField.setText("");
    }//GEN-LAST:event_SClearActionPerformed

    private void FClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FClearActionPerformed
        // TODO add your handling code here:
        FUsernameField.setText("");
        FPasswordField.setText("");
    }//GEN-LAST:event_FClearActionPerformed

    private void AClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AClearActionPerformed
        // TODO add your handling code here:
        AUsernameField.setText("");
        APasswordField.setText("");
    }//GEN-LAST:event_AClearActionPerformed

    private void AloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AloginActionPerformed
        // TODO add your handling code here:
        P3.setValue(0);
        String usr=AUsernameField.getText();
        String pwd=APasswordField.getText();
        P3.setValue(10);
        if("Admin".equals(usr) && "admin123".equals(pwd))
        {
            P3.setValue(100);
            this.dispose();
            new AdminUI().setVisible(true);
        }
        else {
            P3.setValue(0);
            JOptionPane.showMessageDialog(this, "Incorrect Username/Password");
        }
    }//GEN-LAST:event_AloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AClear;
    private javax.swing.JPasswordField APasswordField;
    private javax.swing.JTextField AUsernameField;
    private javax.swing.JButton Alogin;
    private javax.swing.JButton FClear;
    private javax.swing.JButton FLogin;
    private javax.swing.JPasswordField FPasswordField;
    private javax.swing.JTextField FUsernameField;
    private javax.swing.JProgressBar P1;
    private javax.swing.JProgressBar P2;
    private javax.swing.JProgressBar P3;
    private javax.swing.JButton SClear;
    private javax.swing.JPasswordField SPasswordField;
    private javax.swing.JTextField SUsernameField;
    private javax.swing.JButton Slogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
